site_name: Python Notion API
theme:
  logo: img/logo.webp
  favicon: img/logo.webp
  name: material
  palette:
    primary: white
  features:
    - navigation.sections
    - navigation.footer
    - navigation.sections
    - toc.integrate

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Home: index.md
  - Get started:
    - Installation: get_started/install.md
    - Databases: get_started/databases.md
    - Pages: get_started/pages.md
    - Blocks: get_started/blocks.md
