name: Release workflow

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: 'Version number to release in X.Y.Z format'
      dry_run:
        type: boolean
        default: true
        description: 'Dry run'
  pull_request:
    types:
      - closed
    branches:
      - 'fake_develop'
      - 'fake_main'

jobs:
  release_workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Gitflow action
      uses: hoangvvo/gitflow-workflow-action@0.3.7
      with:
        develop_branch: "fake_develop"
        main_branch: "fake_main"
        version: ${{ inputs.version }}
        version_increment: ${{ contains(github.ref, 'refs/heads/hotfix/') && 'patch' || ''   }}
        dry_run: ${{ inputs.dry_run }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}